### ISSUE TITLE
Unittests fail with newer versions of numpy

### ISSUE THREAD

**Issue by jPhy** [fredRos/pypmc#47]
Numpy's random number generator used to accept random seeds larger than 32bit in older versions but silently truncated to 32bit. In newer versions, seeds that exceed 32bit are rejected throwing an error, see https://github.com/numpy/numpy/commit/6b1a1205eac6fe5d162f16155d500765e8bca53c.

The bug can be fixed as described here: https://github.com/lucastheis/c2s/commit/0633333facc64bbb20bd322af96836ae72a22120

**Comment by jPhy** [comment]
resolved in 3cbe43e3feca65c4577bab2b512a7f8dfea91124

**Comment by fredRos** [comment]
fixed in cd10c7a
