### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by JohannesBuchner** [fredRos/pypmc#56]
The link to the documentation gives a 404 not found message mpp page.

**Comment by fredRos** [comment]
I have seen this too, I plan to have travis run the tests automatically, build the docs, and deploy to github.io.It's just not working yet in the last step of deploying the docs Please bear with me

**Comment by JohannesBuchner** [comment]
Thank you! pypmc is awesome!

**Comment by fredRos** [comment]
The problem was with `.gitignore` and I reported it to the doct developers https://github.com/drdoctr/doctr/issues/257 . The docs are now deployed to github.io and I updated the links in the readme
