### ISSUE TITLE
Handle dependencies during installation

### ISSUE THREAD

**Issue by fredRos** [fredRos/pypmc#57]
Right now we require numpy implicitly as it's used in `setup.py`. Follow the solution as for pyfftw to defer installation of dependencies https://github.com/pyFFTW/pyFFTW/blob/master/setup.py

**Comment by fredRos** [comment]
Another option may be this http://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=setup_requires but I'm not sure if it's realiable. Sounds to easy to be right

**Comment by DavidMStraub** [comment]
As discussed: https://github.com/DavidMStraub/rundec-python/commit/ae31a80f6c1897816fb3d04d4aad86855d18b3d8#diff-354f30a63fb0907d4ad57269548329e3 etc.
