### ISSUE TITLE
pypmc from fails to install under Python 3.7

### ISSUE THREAD

**Issue by DavidMStraub** [fredRos/pypmc#62]
Installing `pypmc` with `pip` under Python 3.7 fails, see e.g. [here](https://travis-ci.org/flav-io/flavio/jobs/529803046) for an error log.

I suspect re-generating the Cython files with a more up-to-date Cython version is sufficient to fix it.

(Of course, having wheels on PyPI would be even cooler...)

Cheers!
D.

**Comment by fredRos** [comment]
Ok, I will have a look. I know I haven't tested it with python 3.7, so I"m not surprised it doesn't work.

> (Of course, having wheels on PyPI would be even cooler...)
I remember looking into this but gave up frustrated after a few hours. SOrry

**Comment by fredRos** [comment]
Would you have a problem if I let pypmc depend on cython at install time? Then things should update seamlessly

**Comment by fredRos** [comment]
Af found this related issue, https://github.com/pypa/pip/issues/6193
I should try the pyproject.toml approach for newer pip versions

**Comment by fredRos** [comment]
I created this PR, locally it builds fine in a conda env. with pip19 and python3.7. @DavidMStraub please let me know if that solves the problem. It also fixes building wheels, though I'm not sure that would work for older versions of pip, too

**Comment by DavidMStraub** [comment]
Thanks, looks good! If that makes `cibuildwheel` work that would be awesome.

NB the current version of `cibuildwheel` is 0.11.1, `.travis.yaml` still pins it to the outdated `0.7.0`.

**Comment by fredRos** [comment]
Thanks for the hint. Looks like it builds fine. I had to make a number of adjustments to keep up with new features of travis, pip, cibuildwheels features
When the wheel deployment works, I will create a new minor release

**Comment by fredRos** [comment]
Hey @DavidMStraub I released 1.1.4, please confirm that it works and fixes your issue.
Changing the travis setup was painfully slow due to the huge latency of builds but this setup should carry me a long way into the future I hope

**Comment by DavidMStraub** [comment]
It now works for me after addressing an issue similar to #66 (that I only noticed afterwards). Thanks!
