### ISSUE TITLE
No .tar.gz for v1.1.4 on pypi.org

### ISSUE THREAD

**Issue by dvandyk** [fredRos/pypmc#68]
Tach @fredRos!

Since there is not tar.gz file for the v1.1.4 release on pypi, pip falls back to installing from 1.1.2 source on MacOS. I've worked around that problem for the time being my downloading the tarball and installing from the downloaded file in the EOS CI. However, it would be nice if you could make sure that 1.1.4 and future releases support from-source builds.

**Comment by fredRos** [comment]
That sounds reasonable, sorry for the inconvenience. It's on my TODO list

**Comment by dvandyk** [comment]
@fredRos Pending feedback on #67, this issue and #67 might be linked. Can you please upload the tarball and the wheel for v1.1.4? If you are too busy, I'd be glad to help out.

**Comment by fredRos** [comment]
@dvandyk I finally got round to uploading the source tarball. I don't know how hard/easy it is to create the mac wheel. getting back into this project, it took me one hour just for the source tarball on my new laptop. 

https://files.pythonhosted.org/packages/fc/b6/e41dcf361f54d2c784df9d17443ea80c8f205793feea723c027d36a1c8a6/pypmc-1.1.4.tar.gz

If you have any suggestions for the mac wheel, let me know. I can also grant you access on pypi if you know how to do it.

**Comment by dvandyk** [comment]
I see only the possibility to use Github Actions or Travis CI to run wheel-building on a Mac. Maybe @pluegh is interested to look into this?
